from fpdf import FPDF
import unicodedata

def clean_text(text):
    return unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('ascii')

class PDF(FPDF):
    def header(self):
        # 🎨 Background color for every page
        self.set_fill_color(230, 240, 255)
        self.rect(0, 0, 210, 297, 'F')

    def add_title_bar(self, title_line, subtitle_line):
        # 🏅 Title bar (dark blue)
        self.set_fill_color(70,130,180)
        self.rect(0, 0, 210, 25, 'F')

        self.set_text_color(255, 255, 255)
        self.set_font("Arial", 'B', 18)
        self.set_xy(10, 7)
        self.cell(0, 10, title_line, ln=True)

        self.set_font("Arial", '', 11)
        self.set_x(10)
        self.cell(0, 8, subtitle_line, ln=True)
        self.ln(6)

def generate_resume_pdf(name, email, phone, linkedin, profile, education, projects, skills, soft_skills, extras):
    pdf = PDF()
    pdf.add_page()
    pdf.add_title_bar(name.upper(), f"{phone} | {email} | {linkedin}")

    # 🪄 Section heading helper
    def section(title):
        pdf.set_text_color(70,130,180)
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(0, 8, title, ln=True)
        pdf.set_draw_color(70,130,180)
        pdf.set_line_width(0.6)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(2)
        pdf.set_text_color(40,40,40)
        pdf.set_font("Arial", '', 12)

    # Add sections
    section("Career Objective")
    pdf.multi_cell(0, 8, clean_text(profile))
    pdf.ln(3)

    section("Education")
    pdf.multi_cell(0, 8, clean_text(education))
    pdf.ln(3)

    section("Academic Projects")
    pdf.multi_cell(0, 8, clean_text(projects))
    pdf.ln(3)

    section("Technical Skills")
    pdf.multi_cell(0, 8, clean_text(skills))
    pdf.ln(3)

    section("Soft Skills")
    pdf.multi_cell(0, 8, clean_text(soft_skills))
    pdf.ln(3)

    section("Extra-Curricular Activities")
    pdf.multi_cell(0, 8, clean_text(extras))
    pdf.ln(3)

    pdf.set_y(-15)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(100,100,100)
    pdf.cell(0, 10, 'Generated by AI Resume Builder', 0, 0, 'C')

    file_name = "resume.pdf"
    pdf.output(file_name)
    return file_name

def generate_cover_letter_pdf(name, email, phone, linkedin, cover_letter):
    pdf = PDF()
    pdf.add_page()
    pdf.add_title_bar(f"{name.upper()} - Cover Letter", f"{phone} | {email} | {linkedin}")

    pdf.set_text_color(40,40,40)
    pdf.set_font("Arial", '', 12)
    pdf.multi_cell(0, 8, clean_text(cover_letter))

    pdf.set_y(-15)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(100,100,100)
    pdf.cell(0, 10, 'Generated by AI Resume Builder', 0, 0, 'C')

    file_name = "cover_letter.pdf"
    pdf.output(file_name)
    return file_name